name: Deploy Node Backend (Docker + EC2)

on:
  push:
    branches:
      - main # change to your branch if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t vish2002dil/beautyglow-nodejs-app:latest .

      - name: Push Image to Docker Hub
        run: docker push vish2002dil/beautyglow-nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull vish2002dil/beautyglow-nodejs-app:latest

      - name: Delete old container (if exists)
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            -p 4000:3000 \
            --name nodejs-app-container \
            -e MONGODB_URL=${{ secrets.MONGODB_URL }} \
            -e JWT_KEY=${{ secrets.JWT_KEY }} \
            -e GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }} \
            -e GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }} \
            vish2002dil/beautyglow-nodejs-app:latest
